AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BadSpellingGenerator

Resources:
  bsgBackendService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/
      Handler: index.handler
      Runtime: python3.8
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/spellbad'
            Method: post
